# Generated by Django 5.0.6 on 2024-06-06 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='healthcareworker',
            name='license',
        ),
        migrations.RemoveField(
            model_name='healthcareworker',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='provider',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='reason',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='last_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='description',
            field=models.TextField(default='No description', max_length=10000),
        ),
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='patient',
            name='name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AlterField(
            model_name='patient',
            name='medical_history',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='License',
        ),
        migrations.DeleteModel(
            name='HealthcareWorker',
        ),
    ]
